name: Portfolio CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build and Push docker-compose
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  deploy-server:
    runs-on: ubuntu-latest
    needs: [build_and_push]
    steps:
      - name: SSH into server and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd mhensel
            ./run.sh